#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2015-03-12 15:45:34
# @Author  : Your Name (you@example.org)
# @Link    : http://example.org
# @Version : $Id$

import popen2
import re

stdout, stdin = popen2.popen2("last")
ostr = stdout.read()
for x in ostr:
  print x,
print ostr.find('k')
print ostr[:5]
cnt = ostr.find("k")
newstr = "".join(ostr)
print newstr.find("k")
print "kao login ", cnt,"times!!!"
